# .pre-commit-config.yaml specifies the hooks to be run before all commits

repos:

# isort
- repo: https://github.com/pre-commit/mirrors-isort
  rev: v4.3.21
  hooks:
  - id: isort


# black
- repo: https://github.com/ambv/black
  rev: stable
  hooks:
    - id: black
      args: # arguments to configure black
        - --line-length=88
        - --include='\.pyi?$'
        # these folders wont be formatted by black
        - --exclude="""\.git |
          \.__pycache__|
          \.hg|
          \.mypy_cache|
          \.tox|
          \.venv|
          \venv|
          _build|
          buck-out|
          build|
          dist"""
      language_version: python3


# flake8, check-yaml, end-of-file-fixer, trailing-whitespace
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
    - id: check-yaml
    - id: end-of-file-fixer
    - id: trailing-whitespace
    - id: flake8
      args: # arguments to configure flake8
        - "--select=B,C,E,F,W,T4,B9"
        # we do not want convoluted/over complex logic.
        # E.g https://www.flake8rules.com/rules/C901.html
        - "--max-complexity=10"
        # below are errors that we want flake8 to ignore
        # https://flake8.pycqa.org/en/latest/user/error-codes.html
        - "--ignore=E266,E501,W503"
        - "--max-line-length=88" # making flake8 line length compatible with black
