# Generated by Django 3.2.5 on 2023-01-09 19:28

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Sheet",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=150, null=True)),
                ("mobile", models.CharField(max_length=50, null=True)),
                (
                    "status",
                    models.TextField(
                        choices=[
                            ("Open", "Open"),
                            ("Pending", "Pending"),
                            ("Completed", "Completed"),
                        ],
                        null=True,
                    ),
                ),
                ("address", models.CharField(max_length=150, null=True)),
                ("industry", models.CharField(max_length=150, null=True)),
                ("website", models.CharField(max_length=150, null=True)),
                ("contacts", models.CharField(max_length=150, null=True)),
                ("notes", models.TextField(null=True)),
                (
                    "sheet_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="leads_parser.sheet",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
