# Generated by Django 3.2.5 on 2023-01-10 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads_parser", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="pipelines",
            field=models.TextField(null=True),
        ),
    ]
